✅ 1. Installation
pip install numpy


✅ 2. Mathematical Calculations
python
Copy code
import numpy as np
arr = np.array([1, 2, 3])
print(arr + 1)        # [2 3 4]
print(arr * 2)        # [2 4 6]
print(np.sin(arr))    # [0.841 0.909 0.141]


✅ 3. NumPy Array Creation
python
Copy code
np.array([1, 2, 3])
np.zeros((2, 3))
np.ones((3, 3))
np.eye(3)          # Identity matrix
np.full((2,2), 5)  # Filled with 5


✅ 4. Shape
python
Copy code
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)  # (2, 3)


✅ 5. Indexing
python
Copy code
a = np.array([10, 20, 30])
print(a[1])  # 20


✅ 6. Data Types (Reference)
Code	Meaning
b	boolean
i	integer
u	unsigned integer
f	floating point
c	complex floating point
m	timedelta
M	datetime
O	object
S	string
U	unicode string
V	raw data (void)
a = np.array([1, 2, 3], dtype='f')  # float32


✅ 7. More Creation Methods
python
Copy code
np.arange(1, 10, 2)          # [1 3 5 7 9]
np.linspace(0, 1, 5)         # [0.  0.25 0.5 0.75 1.]
np.diag([1, 2, 3])           # Diagonal matrix


✅ 8. Random Numbers (np.random)
python
Copy code
np.random.rand(2, 3)         # Uniform dist [0,1)
np.random.randn(3)           # Standard normal
np.random.randint(1, 10, 5)  # Random ints from 1 to 9
np.random.random((2, 2))     # Same as rand
np.random.choice([1, 2, 3])  # Randomly pick one
arr = np.array([1, 2, 3])
np.random.shuffle(arr)       # Shuffle inplace
np.random.seed(42)           # Reproducibility


✅ 9. Reshape
python
Copy code
a = np.arange(6).reshape(2, 3)
b = np.arange(8).reshape(2, -1)  # Let NumPy decide column count


✅ 10. Slicing and Assignment
python
Copy code
a = np.array([10, 20, 30, 40])
print(a[1:3])       # [20 30]
a[1:3] = [99, 88]


✅ 11. Copy vs View
python
Copy code
a = np.array([1, 2, 3])
b = a.view()  # Shared memory
c = a.copy()  # Independent copy
a[0] = 10
print(b[0])  # 10
print(c[0])  # 1


✅ 12. Operators (Element-wise)
python
Copy code
a = np.array([True, False])
b = np.array([False, True])
print(a & b)  # [False False]
print(a | b)  # [True True]
print(~a)     # [False  True]


✅ 13. Shape Mismatch
python
Copy code
a = np.array([1, 2])
b = np.array([1, 2, 3])
# print(a + b)  # ❌ Error: shape mismatch


✅ 14. Fancy Indexing (Filtering)
python
Copy code
a = np.array([10, 20, 30, 40])
print(a[[0, 2]])  # [10 30]

# Filtering
print(a[a > 20])  # [30 40]


✅ 15. Search (np.where)
python
Copy code
a = np.array([10, 20, 30])
print(np.where(a > 15))  # (array([1, 2]),)


✅ 16. Basic Reductions
python
Copy code
a = np.array([1, 2, 3, 4])
print(np.sum(a))       # 10
print(np.min(a))       # 1
print(np.max(a))       # 4
print(np.any(a > 3))   # True
print(np.all(a > 0))   # True
print(np.argmax(a))    # 3
print(np.argmin(a))    # 0


✅ 17. Statistics
python
Copy code
a = np.array([1, 2, 3, 4])
print(np.mean(a))      # 2.5
print(np.median(a))    # 2.5
print(np.average(a))   # 2.5
print(np.var(a))       # 1.25
print(np.std(a))       # 1.118


✅ 18. Iteration
python
Copy code
a = np.array([[1, 2], [3, 4]])
for x in np.nditer(a):
    print(x, end=' ')  # 1 2 3 4

for idx, val in np.ndenumerate(a):
    print(idx, val)


✅ 19. Join Arrays
python
Copy code
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.concatenate((a, b), axis=0))
print(np.vstack((a, b)))
print(np.hstack((a, b.T)))


✅ 20. Split Arrays
python
Copy code
a = np.array([1, 2, 3, 4, 5, 6])
print(np.array_split(a, 3))  # 3 chunks


✅ 21. Sort
python
Copy code
a = np.array([3, 1, 2])
print(np.sort(a))  # [1 2 3]


✅ 22. Broadcasting
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]


✅ 23. Input from Text File
# Sample: data.txt contains:
# 1,2,3
# 4,5,6
data = np.loadtxt('data.txt', delimiter=',')

In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4,5]
l2=[[1,2,3],[4,5,6]]
l3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]

In [3]:
l3

[[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18]]]

In [5]:
n1=np.array(l1)
n2=np.array(l2)
n3=np.array(l3)

In [10]:
print(n1,type(n1))
print(n2,type(n2))
print(n3,type(n3))

[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]] <class 'numpy.ndarray'>


In [11]:
n3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [12]:
l3[0][1][2]

6

In [13]:
n3[0,1]

array([4, 5, 6])

In [14]:
n3.shape

(3, 2, 3)

In [15]:

n1.shape

(5,)

In [16]:
n2.shape

(2, 3)

In [ ]:
n3.ndim

# In NumPy, .ndim is an attribute used to find the number
#  of dimensions (axes) of a NumPy array.



3

In [18]:
l3[1]

[[7, 8, 9], [10, 11, 12]]

In [21]:
n3[0,1,1]

np.int64(5)

In [22]:
n3[-1]

array([[13, 14, 15],
       [16, 17, 18]])

In [23]:
n3.dtype

dtype('int64')

In [24]:
# n3 = np.array(l3,dtype='float32')
# n3 = np.array(l3,dtype = 'f8')
n3 = np.array(l3,dtype = 'i8')
n3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [25]:
print(n3[0],type(n3[0]))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [26]:
n3.dtype

dtype('int64')

In [27]:
l = [[1,2,3],[4,5]]
a = np.array(l,dtype='object')
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [28]:
l = [[1,2,3],[4,5]]
a = np.array(l)
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [29]:
a.shape

(2,)

In [30]:
print(a[0],type(a[0]))
a[0] = 100

[1, 2, 3] <class 'list'>


In [31]:
a

array([100, list([4, 5])], dtype=object)

In [32]:
n1 = np.arange(1,11,3,dtype='f4')

In [33]:
n1

array([ 1.,  4.,  7., 10.], dtype=float32)

In [34]:
np.linspace(1,3,7)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        ])

In [35]:
shape = [2,3,3]
np.ones(shape,dtype='i8')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [37]:
np.zeros((3,2,3),dtype='int')

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [38]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [40]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

random numbers: Numpy Random Module
rand: Random values in given shape
randn: Return samples from the Standard normal distribution
randint: Return random integer from low(inclusive) to high(exclusive)
random: Return random floats in [0.0,1.0)
choice: Generates a random sample from given 1D array
Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()


In [ ]:
(30-10)*np.random.rand(4,5)+10
# np.random.rand(4, 5) generates a 4x5 array of random 
# floats in the range [0.0, 1.0).

array([[13.93045819, 18.38985081, 15.50383184, 28.89935638, 10.72876533],
       [29.68110231, 16.16150651, 12.3594235 , 27.53815971, 13.64243594],
       [29.19334806, 27.27750655, 28.76422652, 14.34678179, 14.51376235],
       [10.68921407, 12.24249825, 25.61507258, 25.66237468, 12.19827969]])

In [ ]:
np.random.random(size = (2,3))
# generates a 2×3 NumPy array filled with random float
#  numbers in the range [0.0, 1.0).



array([[0.49483194, 0.64147439, 0.43823976],
       [0.67155374, 0.47733705, 0.41898927]])

In [ ]:
np.random.randn(3,2,3)

# generates a 3-dimensional NumPy array with shape (3, 2, 3), filled with random numbers drawn from the standard normal distribution.

# ✅ What is randn?
# np.random.randn(...) returns samples from a standard normal distribution:

# Mean = 0

# Standard Deviation = 1

# Shape = (3, 2, 3) → 3 "blocks", each of shape (2, 3)



array([[[-1.63103513, -0.40737521,  1.79624423],
        [-0.15569203, -1.08627018, -0.05096451]],

       [[ 0.59192231,  0.40533423,  0.5009361 ],
        [ 1.51602845,  0.78159409, -1.00942522]],

       [[-1.20519937, -1.68356127, -1.16991589],
        [ 0.96630643,  0.08554453,  0.06049275]]])

In [ ]:
np.random.randint(10,20,size=(2,3))
# generates a 2×3 NumPy array filled with random integers
#  in the range [10, 20) — meaning 10 is included, but 20 is
#  excluded.



array([[19, 11, 19],
       [18, 15, 13]], dtype=int32)

In [ ]:
np.random.choice(np.arange(10,21),size=(3,2),p = [0.5,0.1,0,0,0,0,0.2,0.2,0,0,0])

# ✅ Explanation:
# 🔹 np.arange(10, 21)
# This creates the array:

# csharp
# Copy code
# [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# 👉 Length = 11 elements

# 🔹 size=(3, 2)
# You want to generate a 3x2 array of random values selected from [10, 11, ..., 20]

# 🔹 p = [...]
# This is a probability distribution corresponding to each element in [10, 11, ..., 20].

# text

# Values:       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# Probabilities: [0.5, 0.1,  0,   0,   0,   0, 0.2, 0.2,  0,  0,  0]
# Only 10, 11, 16, and 17 have non-zero probability

# So only these values can appear in the result

# Probabilities must sum to 1.0 ✅ (and they do here: 0.5+0.1+0.2+0.2 = 1.0)



array([[11, 10],
       [10, 17],
       [11, 10]])

In [46]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.random.seed(1)
np.random.shuffle(a)
a

# ✅ What it does:
# 1. np.random.seed(1)
# Sets the random seed to ensure reproducibility.
# This means every time you run this code with the same seed and input, you'll get the same shuffled result.

# 2. np.random.shuffle(a)
# Shuffles the array in-place (modifies the original array a).

# If a is a 1D array, elements are shuffled.

# If a is a 2D array, only the rows are shuffled (not columns).

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [48]:
a = np.arange(10,22)
a.shape


(12,)

In [ ]:
b = a.reshape((2,-1,2))

# ✅ Syntax: reshape((2, -1, 2))
# 2: First dimension → split into 2 groups

# -1: Let NumPy automatically calculate this dimension

# 2: Last dimension → each sub-array will have 2 elements



In [50]:
b

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

In [ ]:
b.reshape(-1)

# ✅ What does reshape(-1) mean?
# -1 tells NumPy to infer the dimension automatically.

# When used alone, it reshapes the array into a flat (1D) array containing all the elements.




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [52]:
a = np.arange(100).reshape((10,10))


In [53]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[2:7,3:7]
# ✅ General Syntax for 2D slicing:
# array[row_start:row_end, col_start:col_end]
# This selects:

# Rows from index 2 to 6 (because 7 is exclusive)

# Columns from index 3 to 6 (again, 7 is exclusive)


array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [55]:
a[5:8,::-1]

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70]])

In [56]:
b = a[3:7]
b

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
b[0] = np.arange(1000,1010)
b

# You're assigning a 1D array (np.arange(1000, 1010)) to
#  part of a possibly multi-dimensional array b

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69]])

In [58]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [ ]:
np.shares_memory(a,b)
# Checks whether two NumPy arrays share the same memory
#  (i.e., changes in one may affect the other).



True

In [60]:

c = a[3:7].copy()

In [61]:
c[0] = np.arange(100,110)
c

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]])

In [62]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [63]:
np.shares_memory(a,c)


False

In [ ]:
a[3:6,2:4] = np.arange(200,206).reshape((3,2))
a

# ✅ Step-by-step Explanation
# 🧩 a[3:6, 2:4]
# Selects a submatrix of array a

# Rows from index 3 to 5 (3:6) → 3 rows

# Columns from index 2 to 3 (2:4) → 2 columns

# Resulting shape: (3, 2)

# 🎯 np.arange(200, 206)
# Creates a 1D array: [200, 201, 202, 203, 204, 205] → shape (6,)

# 🔄 .reshape((3, 2))

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001,  200,  201, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,  202,  203,   44,   45,   46,   47,   48,   49],
       [  50,   51,  204,  205,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

operators(Element wise operations)
and: &, or: |, not: ~
shape mismatch
fancy indexing also know as filter
search: where uses fancy indexing
Basic reductions: sum, min, max, any, all,argmax, argmin
Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
iteration: nditer, ndenumerate
Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
split: array_split, hsplit
sort: np.sort
Broadcasting
Input from Text File
Questions

In [66]:
import numpy as np
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
a - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [69]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [70]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [71]:
a // 5

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2])

In [72]:
a % 5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0])

In [73]:
a ** 5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000])

In [74]:
b = np.array([3,2,7,6,1,7,4,8,3])
b >= 5

array([False, False,  True,  True, False,  True, False,  True, False])

In [76]:
a += 5
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
a = np.arange(10)
b = np.arange(10,20)
c = np.arange(20,40)
c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [78]:
a+c

ValueError: operands could not be broadcast together with shapes (10,) (20,) 

In [79]:
a+b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [80]:
a/b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [81]:
a <= b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
a = np.arange(0,10).reshape((5,2))
b = np.arange(0,10).reshape((5,2))

In [83]:
a
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
a+b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [85]:
np.logical_and(a,b)


array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [86]:
(a >= b) | (b > 5)


array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [87]:
np.add(a,b)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [88]:
np.subtract(a,b)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [89]:
np.multiply(a,b)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [90]:
np.multiply(a,b)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [91]:
np.divmod(a,b)

C:\Users\asus\AppData\Local\Temp\ipykernel_8232\3434828917.py:1: RuntimeWarning: divide by zero encountered in divmod
  np.divmod(a,b)


(array([[0, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 array([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]))

In [92]:
x = np.array([1,2,3,4,5,6,7])
m = 2
c = 3
y = m*x+c
print(y)

[ 5  7  9 11 13 15 17]


In [93]:
a = np.arange(10,20)
b = np.arange(10,21)

In [94]:
a[[0,3,9,9]]

array([10, 13, 19, 19])

In [95]:
a = np.arange(100).reshape((10,10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
a = np.arange(100).reshape((10,10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
a[[6,3,8,2]]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [98]:
a[[6,5,2,8],[0,2,4,6]]

array([60, 52, 24, 86])

In [99]:
a[[9,2,0,6],[9,2,0,6]]

array([99, 22,  0, 66])

In [ ]:

a[:,[5,3,8,7]]

# ✅ Breakdown:
# a[:, ...] → means all rows

# [5, 3, 8, 7] → means you're selecting columns 5, 3, 8, and 7, in that specific order

# So you're getting a subset of columns for all rows, reordered.



array([[ 5,  3,  8,  7],
       [15, 13, 18, 17],
       [25, 23, 28, 27],
       [35, 33, 38, 37],
       [45, 43, 48, 47],
       [55, 53, 58, 57],
       [65, 63, 68, 67],
       [75, 73, 78, 77],
       [85, 83, 88, 87],
       [95, 93, 98, 97]])

In [ ]:
a[[6,3,8,2]][:,[2,4,7,9]]

# ✅ Step-by-step Explanation
# Suppose a is a 2D NumPy array with shape (10, 10) or more.

# 🔹 Step 1: a[[6, 3, 8, 2]]
# Selects rows at indices 6, 3, 8, and 2.

# Result: a new array of shape (4, a.shape[1]) — say (4, 10) if a has 10 columns.

# 🔹 Step 2: [..., [2, 4, 7, 9]]
# Selects columns 2, 4, 7, and 9 from those 4 rows.

# Resulting shape: (4, 4)

# ✅ Final Result:
# A 4×4 submatrix containing the intersection of:

# Rows: 6, 3, 8, 2

# Columns: 2, 4, 7, 9



array([[62, 64, 67, 69],
       [32, 34, 37, 39],
       [82, 84, 87, 89],
       [22, 24, 27, 29]])

In [102]:
a = np.array([10,23,31,40,50])
a

array([10, 23, 31, 40, 50])

In [103]:
a[[True,False,True,True,False]]

array([10, 31, 40])

In [104]:
a=np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[[True,False,True,False,True,False,False,True,True,False]]

# print row according to the condition true and false


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
a[:,[True,False,True,False,False,True,False,True,False,False]]

# print all row but specific column with condition given

array([[ 0,  2,  5,  7],
       [10, 12, 15, 17],
       [20, 22, 25, 27],
       [30, 32, 35, 37],
       [40, 42, 45, 47],
       [50, 52, 55, 57],
       [60, 62, 65, 67],
       [70, 72, 75, 77],
       [80, 82, 85, 87],
       [90, 92, 95, 97]])

In [108]:
a[a%3 == 0]

# print all the element in the array a which is divisible by 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [109]:
a[a%5 == 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
a[a[:,0]%4 == 0]


# ✅ Step-by-Step Explanation:
# 🔹 a[:, 0]
# Selects the first column (column at index 0) from all rows.

# 🔹 a[:, 0] % 4 == 0
# Applies the condition: "which values in the first column are divisible by 4?"

# Returns a boolean array (e.g., [False, True, ...])

# 🔹 a[...]
# Filters all rows of a where the condition is True.


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [111]:
a[:,a[0]%4 == 0]

array([[ 0,  4,  8],
       [10, 14, 18],
       [20, 24, 28],
       [30, 34, 38],
       [40, 44, 48],
       [50, 54, 58],
       [60, 64, 68],
       [70, 74, 78],
       [80, 84, 88],
       [90, 94, 98]])

In [112]:
a = np.arange(60).reshape((12,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [113]:
#axis = 0 means mean of column
#axis = 1 means mean of row
np.mean(a,axis = 1)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57.])

In [114]:
np.sum(a,axis = 1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235, 260, 285])

In [115]:
np.max(a)

np.int64(59)

In [116]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [121]:
a

array([[1],
       [2],
       [3]])

In [117]:
a+b

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

In [118]:
a = np.array([[1],[2],[3]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [122]:
a

array([[1],
       [2],
       [3]])

In [123]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [124]:
a+b

array([[11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [125]:
a = np.array([0,1,2,3,4])
b = np.array([[4],[5],[6],[7]])

In [126]:
a

array([0, 1, 2, 3, 4])

In [127]:
b

array([[4],
       [5],
       [6],
       [7]])

In [128]:
a+b

array([[ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [ ]:
a = np.array([10,3,20,4,1])
np.argmax(a)

# This function returns the index of the maximum value in
#  the array a.



np.int64(2)

In [ ]:
data = np.loadtxt('population.txt')
print(data)  


[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [136]:
np.max(data,axis = 0)

array([ 1920., 77400., 59400., 48300.])

In [137]:
np.max(data,axis = 1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [138]:
np.argmax(data,axis = 1)

array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 3, 3, 3])

In [139]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [ ]:
a.dot(b)

# performs a dot product (matrix multiplication)
#  between two NumPy arrays a and b.

array([[19, 22],
       [43, 50]])

In [141]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [142]:
a@b

array([[19, 22],
       [43, 50]])