Part-I Numpy Questions
Objective:
To build a strong foundation in using NumPy for numerical computations,
including creating arrays, performing operations, and leveraging its
powerful functionalities.

Task 1: Creating Arrays
1. Write a Python program to:
--> Create a 1D NumPy array of 10 integers ranging from 1 to 10.
--> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
--> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array

In [7]:
import numpy as np
l1=np.random.randint(1,11,10)
print(l1.shape)
print(l1.size)
print(type(l1))
l1


(10,)
10
<class 'numpy.ndarray'>


array([1, 3, 6, 3, 9, 6, 4, 9, 3, 9], dtype=int32)

In [9]:
import numpy as np
l2=np.random.randint(1,10,9).reshape(3,3)
print(l2.shape)
print(l2.size)
print(type(l2))
l2

(3, 3)
9
<class 'numpy.ndarray'>


array([[2, 8, 5],
       [1, 5, 4],
       [8, 5, 7]], dtype=int32)

In [13]:
import numpy as np
l3=np.random.rand(3,5,3)
print(l3.shape)
print(l3.size)
print(type(l3))
l3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.20944813, 0.1141704 , 0.33900474],
        [0.54156809, 0.77270845, 0.45054271],
        [0.39776692, 0.1799548 , 0.05853813],
        [0.63438989, 0.41184282, 0.40815208],
        [0.76736878, 0.49996463, 0.94202117]],

       [[0.4741844 , 0.70248061, 0.2414695 ],
        [0.59260942, 0.69936831, 0.49976674],
        [0.85876242, 0.18048776, 0.09070577],
        [0.83280531, 0.01062013, 0.60703839],
        [0.46561512, 0.44748443, 0.06638304]],

       [[0.61275257, 0.28598363, 0.72974437],
        [0.12026133, 0.31520549, 0.36639818],
        [0.18758917, 0.38782425, 0.19296345],
        [0.50659899, 0.13068912, 0.17745502],
        [0.54281253, 0.74151839, 0.32675268]]])

Task 2: Array Indexing and Slicing:-

1. Create a NumPy array from the following list:
-->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to:
-->Retrieve the first three elements of the array.
-->Retrieve every alternate element of the array.
-->Reverse the array.
3. Perform the above operations and display the results

In [17]:
import numpy as np
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
l1=np.array(data)
print(l1[0:3])
print(l1[::2])
print(l1[::-1])


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations:-
1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

2. Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise.
--> Compute the dot product of the arrays.
--> Find the mean, median, standard deviation, and variance o--> array A.
--> Identify the maximum and minimum values in array B and their indices

In [26]:
# Add, subtract, multiply, and divide the two arrays element-wise.
import numpy as np
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition :",add)
print("Subtraction :",sub)
print("Multiplication :",mul)
print("Division:",div)

[13  8 14  2 19]
[17  1 19 19  6]
Addition : [30  9 33 21 25]
Subtraction : [ -4   7  -5 -17  13]
Multiplication : [221   8 266  38 114]
Division: [0.76470588 8.         0.73684211 0.10526316 3.16666667]


In [23]:
# Compute the dot product of the arrays.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
dot_product = np.dot(A, B)
# Or alternatively:
# dot_product = A @ B
print(dot_product)


[14 10  6 12  5]
[ 7 16  2 19 18]
588


In [25]:
# Find the mean, median, standard deviation, and variance o--> array A.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print("Mean :",np.mean(A))
print("Median :",np.median(A))
print("Standard deviation :",np.std(A))
print("Varience :",np.var(A))


[10  5 10  7 14]
Mean : 9.2
Median : 10.0
Standard deviation : 3.059411708155671
Varience : 9.36


In [27]:
# Identify the maximum and minimum values in array B and their indices
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(B)
print("Maximum :",np.max(B))
print("Minimum :",np.min(B))
print("Maximum idx :",np.argmax(B))
print("Minimum idx :",np.argmin(B))

[18 19 11  1  5]
Maximum : 19
Minimum : 1
Maximum idx : 1
Minimum idx : 3


Task 4: Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:
-->Reshape the array into a 2D array of shape (4, 3).
-->Reshape the array into a 3D array of shape (2, 2, 3).
-->Transpose the reshaped 2D array and display its shape.

In [40]:
import numpy as np

l1=np.random.randint(1,12,12)
print(l1)
print("2D Array of Size 4X3")
print(l1.reshape(4,3))
print("3D Array of Size 2X2X3  ")
print(l1.reshape(2,2,3))
print("Transpose of 2D Array")
print(np.transpose(l1.reshape(4,3)))
print("Transpose of 2D Array and its shape")
print(np.transpose(l1.reshape(4,3)).shape)


[ 8  9  6  4 10  3  9  4  2  7  9  6]
2D Array of Size 4X3
[[ 8  9  6]
 [ 4 10  3]
 [ 9  4  2]
 [ 7  9  6]]
3D Array of Size 2X2X3  
[[[ 8  9  6]
  [ 4 10  3]]

 [[ 9  4  2]
  [ 7  9  6]]]
Transpose of 2D Array
[[ 8  4  9  7]
 [ 9 10  4  9]
 [ 6  3  2  6]]
Transpose of 2D Array and its shape
(3, 4)


Task 5: Boolean Masking and Filtering:-

1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:
-->Find all elements greater than 25.
-->Replace all elements less than 30 with 0.
-->Count the number of elements divisible by 5.

In [60]:
import numpy as np

l2=np.random.randint(10,50,15)
print(l2)
print("Numbers Greater than 25 :")
print(l2[l2>25])
print("Replacing all elements less than 30 with 0 :")
l2[l2<30]=0
print(l2)
print("number of nonZero elements divisible by 5")
print(np.count_nonzero(l2[l2%5==0]))
print("number of  elements divisible by 5")
print(np.count_nonzero(l2%5==0))


[48 36 27 18 11 13 40 48 34 20 16 36 11 24 46]
Numbers Greater than 25 :
[48 36 27 40 48 34 36 46]
Replacing all elements less than 30 with 0 :
[48 36  0  0  0  0 40 48 34  0  0 36  0  0 46]
number of nonZero elements divisible by 5
1
number of  elements divisible by 5
9


Task 6: Working with Built-in Functions:-

1. Use NumPy's built-in functions to:
-->Create an array of 10 equally spaced values between 0 and 1.
-->Create an identity matrix of size 4x4.
-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [ ]:
# Create an array of 10 equally spaced values between 0 and 1.
import numpy as np
l1=np.linspace(0,1,10)
print("Array of 10 equally spaced values between 0 and 1 \n")
print(l1)

Array of 10 equally spaced values between 0 and 1 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [67]:
# Create an identity matrix of size 4x4.
import numpy as np
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [77]:
# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

import numpy as np
l3=np.random.randint(1,100,20)
print("Original Array :-")
print(l3)
print("Sorted Array :-")
print(np.sort(l3))
print("5 largest elements")
print(np.sort(l3)[-5:][::-1])

Original Array :-
[90 44 21  1 43 16 12 64 48 33 10 75 63 15 48 44 47 64 58 63]
Sorted Array :-
[ 1 10 12 15 16 21 33 43 44 44 47 48 48 58 63 63 64 64 75 90]
5 largest elements
[90 75 64 64 63]


Task 7: Generic:-

1. Create a Python program that:
-->Generates two large random arrays of size (100, 100).
-->Performs matrix multiplication on the two arrays.
-->Finds the determinant and inverse of the resulting matrix (if possible).
-->Measures the time taken to complete these operations.

In [89]:
import numpy as np
import time

# Step 1: Generate two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Start the timer
start_time = time.time()
print(f"Operation Start time :{start_time} \n")

# Step 3: Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication completed.\n")
print(C,"\n")


# Step 4: Calculate determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")


# Step 5: Try to calculate inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True

# Step 6: End the timer
end_time = time.time()
print(f"Operation end time :{end_time} \n")

elapsed_time = end_time - start_time

# Step 7: Print results
print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {elapsed_time:.4f} seconds")


Operation Start time :1751652537.6609411 

Matrix multiplication completed.

[[26.4601817  26.47685546 25.83436237 ... 26.72032976 25.9993785
  24.03310171]
 [25.74721092 25.1406355  26.0826706  ... 27.53715657 25.6710559
  23.94330322]
 [22.74633226 23.50352504 23.53090917 ... 25.22576455 22.3266705
  22.46491098]
 ...
 [25.10892647 23.8649277  23.60950098 ... 25.47519132 23.65322513
  23.10770176]
 [25.19401758 24.30116987 25.7187958  ... 25.61652499 24.17607341
  23.88237298]
 [26.36444608 25.8408668  26.79977312 ... 27.0247361  26.46634642
  23.11083803]] 

Determinant of the result: -2.363446161715872e+49 

Operation end time :1751652537.7554245 

Matrix is invertible.
Inverse matrix calculated successfully.
[[ 3.99279510e-02 -3.18502334e-01  4.00526252e+00 ... -4.00843455e+00
   9.09597981e-02 -1.68982973e+00]
 [-5.83424723e+00 -7.27724759e-02  4.61295711e+01 ... -4.52193287e+01
   6.02412881e+00 -1.68649112e+01]
 [-1.08508803e+01 -7.25944045e-01  8.20014573e+01 ... -8.23163009e+